-- 0021_add_subscription_id_to_contract_objects.down.sql
-- no-down available — миграция применена один раз и не предполагает отката
-- (если потребуется откат, написать вручную DROP COLUMN/TABLE/INDEX)
